local root = vim.fn.getcwd()
local nvim_lint_root = vim.env.NVIM_NVDA_NVIM_LINT_ROOT
local ale_root = vim.env.NVIM_NVDA_ALE_ROOT
local fixture_root = vim.env.NVIM_NVDA_LINTER_TEST_ROOT
local provider = vim.env.NVIM_NVDA_LINTER_PROVIDER

assert(type(nvim_lint_root) == "string" and vim.fn.isdirectory(nvim_lint_root) == 1,
  "NVIM_NVDA_NVIM_LINT_ROOT must name an nvim-lint checkout")
assert(type(ale_root) == "string" and vim.fn.isdirectory(ale_root) == 1,
  "NVIM_NVDA_ALE_ROOT must name an ALE checkout")
assert(type(fixture_root) == "string" and vim.fn.isdirectory(fixture_root) == 1,
  "NVIM_NVDA_LINTER_TEST_ROOT must name an isolated directory")
assert(provider == "nvim-lint" or provider == "ale",
  "NVIM_NVDA_LINTER_PROVIDER must be nvim-lint or ale")

nvim_lint_root = vim.fn.fnamemodify(nvim_lint_root, ":p")
ale_root = vim.fn.fnamemodify(ale_root, ":p")
local provider_root = provider == "nvim-lint" and nvim_lint_root or ale_root
for _, value in ipairs({ root .. "/neovim-plugin", provider_root }) do
  vim.opt.runtimepath:prepend(value)
  package.path = value .. "/lua/?.lua;" .. value .. "/lua/?/init.lua;" .. package.path
end

local assertions = 0
local function truth(value, label)
  assertions = assertions + 1
  assert(value, label)
end

local cases = {
  {
    name = "clangtidy",
    directory = "c",
    file = "broken.c",
    filetype = "c",
    lines = { "int main(void) { return missing; }" },
    source = provider == "nvim-lint" and "clang-tidy" or "clangtidy",
    code = provider == "nvim-lint" and "clang-diagnostic-error" or nil,
    message_pattern = provider == "ale" and "%[clang%-diagnostic%-error%]" or nil,
  },
  {
    name = "ruff",
    directory = "python",
    file = "broken.py",
    filetype = "python",
    lines = { "import os", "print(missing)" },
    source = "ruff",
    code = "F821",
  },
  {
    name = "shellcheck",
    directory = "bash",
    file = "broken.sh",
    filetype = "sh",
    lines = { "#!/bin/bash", 'value="hello world"', "echo $value" },
    source = "shellcheck",
    code = provider == "nvim-lint" and 2086 or "SC2086",
  },
  {
    name = "staticcheck",
    directory = "go",
    file = "broken.go",
    filetype = "go",
    lines = {
      "package main",
      "",
      "func enabled(value bool) bool {",
      "\tif value == true {",
      "\t\treturn true",
      "\t}",
      "\treturn false",
      "}",
      "",
      "func main() {",
      "\t_ = enabled(true)",
      "}",
    },
    source = "staticcheck",
    source_missing = provider == "nvim-lint",
    code = provider == "nvim-lint" and "S1002" or nil,
    message_pattern = provider == "ale" and "S1002" or nil,
  },
  {
    name = provider == "nvim-lint" and "clippy" or "cargo",
    directory = "rust",
    file = "src/main.rs",
    filetype = "rust",
    lines = {
      "fn main() {",
      "    let values = vec![1, 2, 3];",
      "    if values.len() == 0 {",
      '        println!("empty");',
      "    }",
      "}",
    },
    source = provider == "nvim-lint" and "clippy" or "cargo",
    message_pattern = "length comparison to zero",
  },
  {
    name = "rubocop",
    directory = "ruby",
    file = "broken.rb",
    filetype = "ruby",
    lines = {
      "def greet",
      '  puts "hello"',
      "end",
    },
    source = "rubocop",
    code = "Style/StringLiterals",
  },
  {
    name = provider == "nvim-lint" and "markdownlint-cli2" or "markdownlint",
    directory = "markdown",
    file = "broken.md",
    filetype = "markdown",
    lines = {
      "# First heading",
      "",
      "# Second heading",
    },
    source = "markdownlint",
    code = provider == "ale" and "MD025/single-title/single-h1" or nil,
    message_pattern = provider == "nvim-lint" and "MD025" or nil,
  },
}

for _, directory in ipairs({ "c", "python", "bash", "go", "rust/src", "ruby", "markdown" }) do
  truth(vim.fn.mkdir(fixture_root .. "/" .. directory, "p") == 1,
    "create " .. directory .. " fixture directory")
end
truth(vim.fn.writefile({ "Checks: 'clang-analyzer-*'" },
  fixture_root .. "/c/.clang-tidy") == 0, "write isolated Clang-Tidy configuration")
truth(vim.fn.writefile({ "module access_link_lint_fixture", "", "go 1.26.0" },
  fixture_root .. "/go/go.mod") == 0, "write isolated Go module")
truth(vim.fn.writefile({
  "[package]",
  'name = "access_link_lint_fixture"',
  'version = "0.1.0"',
  'edition = "2024"',
}, fixture_root .. "/rust/Cargo.toml") == 0, "write isolated Cargo manifest")
truth(vim.fn.writefile({
  "# This file is automatically @generated by Cargo.",
  "# It is not intended for manual editing.",
  "version = 4",
  "",
  "[[package]]",
  'name = "access_link_lint_fixture"',
  'version = "0.1.0"',
}, fixture_root .. "/rust/Cargo.lock") == 0, "write isolated Cargo lockfile")
truth(vim.fn.writefile({
  "AllCops:",
  "  NewCops: enable",
  "  SuggestExtensions: false",
  "Style/StringLiterals:",
  "  EnforcedStyle: single_quotes",
}, fixture_root .. "/ruby/.rubocop.yml") == 0, "write isolated RuboCop configuration")
truth(vim.fn.writefile({
  "{",
  '  "default": false,',
  '  "MD025": true',
  "}",
}, fixture_root .. "/markdown/.markdownlint.json") == 0,
  "write isolated markdownlint configuration")
for _, case in ipairs(cases) do
  truth(vim.fn.writefile(
    case.lines, fixture_root .. "/" .. case.directory .. "/" .. case.file) == 0,
    "write " .. case.file)
end

if provider == "ale" then
  vim.g.ale_linters_explicit = 1
  vim.g.ale_linters = {
    c = { "clangtidy" },
    python = { "ruff" },
    sh = { "shellcheck" },
    go = { "staticcheck" },
    rust = { "cargo" },
    ruby = { "rubocop" },
    markdown = { "markdownlint" },
  }
  vim.g.ale_rust_cargo_use_clippy = 1
  vim.g.ale_rust_cargo_target_dir = fixture_root .. "/rust/target"
  vim.g.ale_go_staticcheck_use_global = 1
  vim.g.ale_markdown_markdownlint_executable = "markdownlint-cli2"
  vim.g.ale_lint_on_enter = 0
  vim.g.ale_lint_on_filetype_changed = 0
  vim.g.ale_lint_on_insert_leave = 0
  vim.g.ale_lint_on_save = 0
  vim.g.ale_lint_on_text_changed = "never"
  vim.g.ale_lint_on_text_changed_insert = "never"
  vim.g.ale_echo_cursor = 0
  vim.g.ale_use_neovim_diagnostics_api = 1
  vim.cmd("runtime plugin/ale.vim")
else
  truth(type(require("lint").try_lint) == "function",
    "nvim-lint exposes its documented lint entry point")
end

local diagnostic_events = {}
vim.api.nvim_create_autocmd("DiagnosticChanged", {
  callback = function(args)
    diagnostic_events[args.buf] = (diagnostic_events[args.buf] or 0) + 1
  end,
})

local access_diagnostics = require("nvim_nvda.diagnostics")
local severity_names = {
  [vim.diagnostic.severity.ERROR] = "error",
  [vim.diagnostic.severity.WARN] = "warning",
  [vim.diagnostic.severity.INFO] = "information",
  [vim.diagnostic.severity.HINT] = "hint",
}
local function matches(case, diagnostic)
  local native_source
  if not case.source_missing then
    native_source = case.source
  end
  return diagnostic.source == native_source and diagnostic.code == case.code
    and (not case.message_pattern or diagnostic.message:find(case.message_pattern))
end

for _, case in ipairs(cases) do
  local case_root = fixture_root .. "/" .. case.directory
  vim.cmd("lcd " .. vim.fn.fnameescape(case_root))
  vim.cmd("edit " .. vim.fn.fnameescape(case_root .. "/" .. case.file))
  local buffer = vim.api.nvim_get_current_buf()
  vim.bo[buffer].filetype = case.filetype
  vim.diagnostic.reset(nil, buffer)
  diagnostic_events[buffer] = 0

  if provider == "ale" then
    local linted_before = vim.fn.getbufvar(buffer, "ale_linted", 0)
    vim.cmd("ALELint")
    local completed = vim.wait(15000, function()
      return vim.fn.getbufvar(buffer, "ale_linted", 0) > linted_before
    end, 20)
    if not completed then
      print(case.name .. " incomplete ALE history: "
        .. vim.inspect(vim.fn.getbufvar(buffer, "ale_history", {})))
    end
    truth(completed, case.name .. " ALE run completes")
  else
    require("lint").try_lint(case.name, { cwd = case_root })
    local published = vim.wait(15000, function()
      for _, diagnostic in ipairs(vim.diagnostic.get(buffer)) do
        if matches(case, diagnostic) then return true end
      end
      return false
    end, 20)
    if not published then
      print(case.name .. " diagnostics: " .. vim.inspect(vim.diagnostic.get(buffer)))
    end
    truth(published, case.name .. " nvim-lint run publishes its target diagnostic")
  end

  if provider == "ale" then
    vim.wait(2000, function()
      for _, diagnostic in ipairs(vim.diagnostic.get(buffer)) do
        if matches(case, diagnostic) then return true end
      end
      return false
    end, 20)
  end

  local target
  for _, diagnostic in ipairs(vim.diagnostic.get(buffer)) do
    if matches(case, diagnostic) then
      target = diagnostic
      break
    end
  end
  if not target then
    print(case.name .. " unmatched diagnostics: "
      .. vim.inspect(vim.diagnostic.get(buffer)))
  end
  truth(type(target) == "table",
    case.name .. " publishes its provider identity through vim.diagnostic")
  truth(type(target.message) == "string" and target.message ~= "",
    case.name .. " publishes a nonempty message")
  truth(type(severity_names[target.severity]) == "string",
    case.name .. " publishes a recognized severity")
  truth(type(target.lnum) == "number" and type(target.col) == "number"
    and type(target.end_lnum) == "number" and type(target.end_col) == "number",
    case.name .. " publishes a complete range")
  truth((diagnostic_events[buffer] or 0) > 0,
    case.name .. " produces a DiagnosticChanged event")

  vim.api.nvim_win_set_cursor(0, { target.lnum + 1, target.col })
  local snapshot, count = access_diagnostics.snapshot(buffer, target.lnum + 1, target.col)
  truth(count > 0 and type(snapshot) == "table",
    case.name .. " reaches the Access Link diagnostic snapshot")
  truth(snapshot.source == case.source and snapshot.code == case.code,
    case.name .. " preserves provider identity and diagnostic code")
  truth(snapshot.message == target.message and snapshot.severity == severity_names[target.severity],
    case.name .. " preserves message and severity")
  truth(snapshot.line == target.lnum + 1 and snapshot.byteColumn == target.col,
    case.name .. " preserves the native byte-range start")
  truth(snapshot.endLine == target.end_lnum + 1 and snapshot.endByteColumn == target.end_col,
    case.name .. " preserves the native byte-range end")
  truth(type(snapshot.index) == "number" and type(snapshot.count) == "number"
    and snapshot.index >= 1 and snapshot.index <= snapshot.count,
    case.name .. " publishes a valid provider-neutral position")
end

print(string.format("real %s linter integration: %d assertions passed", provider, assertions))
vim.cmd("qa!")
