local root = vim.fn.getcwd()
package.path = root .. "/neovim-plugin/lua/?.lua;" .. root .. "/neovim-plugin/lua/?/init.lua;" .. package.path
local selection = dofile(root .. "/neovim-plugin/lua/nvim_nvda/selection.lua")
local state = dofile(root .. "/neovim-plugin/lua/nvim_nvda/state.lua")

local function equal(expected, actual, label)
  assert(expected == actual, string.format("%s: expected %s, got %s", label, vim.inspect(expected), vim.inspect(actual)))
end

local lines = { [1] = "a界🙂z", [2] = "second", [3] = "third" }
local forward = selection.from_positions(lines, "v", { line = 1, byteColumn = 1 }, { line = 1, byteColumn = 4 })
equal("forward", forward.direction, "forward direction")
equal(8, forward.finish.byteColumn, "emoji inclusive byte end")

local backward = selection.from_positions(lines, "v", { line = 2, byteColumn = 3 }, { line = 1, byteColumn = 1 })
equal("backward", backward.direction, "backward direction")
equal(1, backward.start.line, "normalized start line")
equal(4, backward.finish.byteColumn, "ASCII inclusive end")

local linewise = selection.from_positions(lines, "V", { line = 3, byteColumn = 2 }, { line = 1, byteColumn = 1 })
equal("line", linewise.kind, "line kind")
equal(3, linewise.lineCount, "line count")
equal(#lines[3], linewise.finish.byteColumn, "line end")

local block = selection.from_positions(lines, "\22", { line = 1, byteColumn = 5 }, { line = 3, byteColumn = 2 })
equal("block", block.kind, "block kind")
equal(2, block.start.byteColumn, "block left")
equal(5, block.finish.byteColumn, "block right")

local exclusive = selection.from_positions(lines, "v", { line = 1, byteColumn = 1 }, { line = 1, byteColumn = 4 }, "exclusive")
equal(4, exclusive.finish.byteColumn, "exclusive end")

equal("normal", state.normalize_mode("n"), "normal mode")
equal("normal", state.normalize_mode("niI"), "normal insert mode")
equal("operatorPending", state.normalize_mode("no"), "operator pending")
equal("insert", state.normalize_mode("ic"), "insert completion")
equal("replace", state.normalize_mode("Rv"), "virtual replace")
equal("visualCharacter", state.normalize_mode("v"), "visual character")
equal("visualLine", state.normalize_mode("V"), "visual line")
equal("visualBlock", state.normalize_mode("\22"), "visual block")
equal("commandLine", state.normalize_mode("cv"), "command line")
equal("terminal", state.normalize_mode("t"), "terminal")

vim.api.nvim_buf_set_lines(0, 0, -1, true, { "\t界🙂z" })
vim.bo.tabstop = 4
vim.bo.shiftwidth = 4
vim.api.nvim_win_set_cursor(0, { 1, 0 })
vim.cmd("normal! v2l")
local visual_state = state.snapshot("test")
equal("visualCharacter", visual_state.mode, "snapshot visual mode")
equal(4, visual_state.tabstop, "snapshot tabstop")
equal(4, visual_state.shiftwidth, "snapshot shiftwidth")
equal(0, visual_state.selection.currentLine.startByteColumn, "snapshot selection start")
equal(8, visual_state.selection.currentLine.endByteColumn, "snapshot selection end")
equal("\t界🙂", visual_state.selection.text, "snapshot character selection text")
vim.cmd("normal! \27")
vim.api.nvim_buf_set_lines(0, 0, -1, true, { "Petra war einkaufen.", "Zweite Zeile", "Dritte Zeile" })
vim.api.nvim_win_set_cursor(0, { 1, 0 })
vim.cmd("normal! Vj")
local visual_line_state = state.snapshot("testLine")
equal("line", visual_line_state.selection.kind, "snapshot line selection kind")
equal(2, #visual_line_state.selection.selectedLines, "snapshot line selection count")
equal("Petra war einkaufen.", visual_line_state.selection.selectedLines[1].text, "snapshot first selected line")
equal("Zweite Zeile", visual_line_state.selection.selectedLines[2].text, "snapshot second selected line")
vim.cmd("normal! \27")
vim.api.nvim_win_set_cursor(0, { 1, 0 })
vim.cmd("normal! \22jl")
local visual_block_state = state.snapshot("testBlock")
equal("block", visual_block_state.selection.kind, "snapshot block selection kind")
equal("Pe\nZw", visual_block_state.selection.text, "snapshot block selection text")
vim.cmd("normal! \27")
vim.api.nvim_buf_set_lines(0, 0, -1, true, { "" })
vim.api.nvim_win_set_cursor(0, { 1, 0 })
vim.cmd("normal! V")
local empty_line_state = state.snapshot("testEmptyLine")
equal("line", empty_line_state.selection.kind, "empty line selection kind")
equal(1, #empty_line_state.selection.selectedLines, "empty line selection count")
equal("", empty_line_state.selection.text, "empty line selection text")
vim.cmd("normal! \27")
vim.api.nvim_buf_set_lines(0, 0, -1, true, { "界🙂", "x" })
vim.api.nvim_win_set_cursor(0, { 1, 0 })
vim.cmd("normal! \22jl")
local unicode_block_state = state.snapshot("testUnicodeBlock")
equal("界\nx", unicode_block_state.selection.text, "unicode ragged block text")
equal(1, unicode_block_state.tabIndex, "tab index")
equal(1, unicode_block_state.tabCount, "tab count")
equal(1, unicode_block_state.windowIndex, "window index")
equal(1, unicode_block_state.windowCount, "window count")
equal("normal", unicode_block_state.windowType, "normal window type")
print("selection/state tests: 44 assertions passed")
vim.cmd("qa!")
